# -*- coding: utf-8 -*-
"""ITR_PROPRIEDADES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpL_1CK-kIwAQ3nXbmjXw8qzddMvkJj2

<div style="text-align: center; font-size: 35px;">
    <font color="blue">Cálculos de ITR</font>
</div>
"""
####################################
###   VERSÃO 23072026
####################################

import os
import pandas as pd
import pdfplumber
import matplotlib.pyplot as plt
import requests
import unidecode  # Biblioteca para remover acentos
import numpy as np
import streamlit as st
import plotly.express as px
import gdown  # para baixar arquivos do Google Drive

st.title("Dashboard ITR - Imposto Territorial Rural")

# Funções auxiliares para ajuste de formato numérico
def ajustar_formato_numerico_area_total(valor):
    return float(valor.replace('.', '').replace(',', '.')) if pd.notnull(valor) else valor

def ajustar_percentual_detencao(valor):
    return float(valor) / 100 if pd.notnull(valor) else valor

# ================================
# DOWNLOAD DIRETO DO GOOGLE DRIVE
# ================================
# MAPBIOMAS.xlsx
file_path_mapbiomas = "https://drive.google.com/uc?id=1iqJIm6vMlsgWrVpbZ8qyyF7iozWKNrNS"
output_mapbiomas = "MAPBIOMAS.xlsx"
gdown.download(file_path_mapbiomas, output_mapbiomas, quiet=False)

# CODIGO MUNICIPIOS.xlsx
file_path_codes = "https://drive.google.com/uc?id=1OnPYWxQu9K1L0upucj3aPENgEHM6RNEI"
output_codes = "CODIGO_MUNICIPIOS.xlsx"
gdown.download(file_path_codes, output_codes, quiet=False)

# Carregar o arquivo Excel MAPBIOMAS - leitura sem cabeçalho
xls = pd.ExcelFile(file_path_mapbiomas)
df_raw = pd.read_excel(xls, sheet_name="Dados", header=None)

# Renomear colunas automaticamente
df_raw.columns = [f"col{i}" for i in range(len(df_raw.columns))]   # MAPBIMOAS 8 COLUNAS

# Normalizar nomes de municípios
df_raw["col0"] = df_raw["col0"].astype(str).str.strip()

# Palavras-chave relacionadas à floresta
forest_related_keywords = [
    "1. Forest",
    "1.1. Forest Formation",
    "1.2. Savanna Formation",
    "1.4 Floodable Forest"
]

# Agrupar por município
data = []
for municipio, grupo in df_raw.groupby("col0"):
    floresta_value = grupo[grupo["col3"].isin(forest_related_keywords)]["col7"].sum()
    pastagem_value = grupo[grupo["col4"].str.contains("3.1. Pasture", na=False)]["col7"].sum()
    silvicultura_value = grupo[grupo["col4"].str.contains("3.3. Forest Plantation", na=False)]["col7"].sum()
    lavouras_value = grupo[grupo["col4"].str.contains("3.2. Agriculture", na=False)]["col7"].sum()

    area_total = floresta_value + pastagem_value + silvicultura_value + lavouras_value
    data.append([municipio, area_total, floresta_value, pastagem_value, silvicultura_value, lavouras_value])

# Criar DataFrame final
columns = ["MunicípioUF", "Área Total", "Floresta", "Pastagem", "Silvicultura", "Lavouras"]
df_final = pd.DataFrame(data, columns=columns)

################################################################
# Carregar e processar os códigos dos municípios com cabeçalho #
################################################################
xls2 = pd.ExcelFile(file_path_codes)
df_codes = pd.read_excel(xls2, sheet_name="Sheet1")

df_codes.rename(
    columns={
        df_codes.columns[1]: 'Código IBGE',
        df_codes.columns[2]: 'Município',
        df_codes.columns[3]: 'UF'
    },
    inplace=True
)
df_codes.drop(df_codes.columns[0], axis=1, inplace=True)

# Criar a coluna MunicípioUF em df_codes
df_codes["MunicípioUF"] = df_codes["Município"] + " - " + df_codes["UF"]

# Normalizar nomes de municípios
df_codes["MunicípioUF"] = df_codes["MunicípioUF"].astype(str).str.strip()

# Mesclar dados do MAPBIOMAS com códigos IBGE
Mapbiomas_municípios = pd.merge(df_codes, df_final,
                          on="MunicípioUF",
                          how="right")

Mapbiomas_municípios.info()

  # Completando Código IBGE de 5 municípios não constantes do arquivo de municípios
valores_corrigir = {
    "Lagoa dos Patos - RS": {"Município": "Lagoa dos Patos", "Código IBGE": 4300002, "UF":"RS"},
    "Lagoa Mirim - RS":     {"Município": "Lagoa Mirim",     "Código IBGE": 4300001, "UF":"RS"},
    "São Luiz - RR":        {"Município": "São Luiz",        "Código IBGE": 1400605, "UF":"RR"},
    "Açu - RN":             {"Município": "Açu",             "Código IBGE": 2400201, "UF":"RN"},
    "Arês - RN":            {"Município": "Arês",            "Código IBGE": 2401206, "UF":"RN"}
}
for MunicipioUF, valores in valores_corrigir.items():
    mask = Mapbiomas_municípios["MunicípioUF"] == MunicipioUF
    for coluna, valor in valores.items():
        Mapbiomas_municípios.loc[mask, coluna] = valor

for municipioUF, valores in valores_corrigir.items():
    mask = Mapbiomas_municípios["MunicípioUF"] == municipioUF
    for coluna, valor in valores.items():
        Mapbiomas_municípios.loc[mask, coluna] = valor

"""# Carregando TABELA VTN 2025, merge com Municípios"""

import pdfplumber
import pandas as pd
import gdown
import unidecode  # Necessário para a função normalizar_texto

# ==========================================
# 1. DEFINIÇÃO DE FUNÇÕES AUXILIARES
# (Devem vir ANTES da função principal que as usa)
# ==========================================

def normalizar_texto(texto):
    if pd.isna(texto):
        return None
    return unidecode.unidecode(str(texto)).upper().strip()


def converter_para_float(valor):
    if isinstance(valor, str):
        valor = valor.replace("R$", "").replace(".", "").replace(",", ".").strip()
        try:
            return float(valor)
        except ValueError:
            return None
    return None


# ==========================================
# 2. DEFINIÇÃO DA FUNÇÃO PRINCIPAL DE EXTRAÇÃO
# ==========================================

def extrair_dados_pdf_formatado(caminho_pdf):
    # Carregar a planilha de referência - aproveitando arquivo de municípios atualizados já baixado
    df_xlsx = df_codes.copy()

    # Criar chave de mapeamento: "MUNICÍPIO - UF" - tudo maiúsculo como em Planilha VTN
    df_xlsx["Nome_Normalizado"] = (
        df_xlsx["Município"].apply(normalizar_texto) + " - " + df_xlsx["UF"].str.upper()
    )
    # Criar dicionário para mapear "MUNICÍPIO - UF" → Sigla correta
    mapeamento_municipios = dict(zip(df_xlsx["Nome_Normalizado"], df_xlsx["MunicípioUF"]))

    with pdfplumber.open(caminho_pdf) as pdf:
        dados = []

        # Percorrer todas as páginas do PDF
        for pagina in pdf.pages:
            tabelas = pagina.extract_tables()

            # Percorrer todas as tabelas encontradas
            for tabela in tabelas:
                for linha in tabela:
                    # Ignorar cabeçalhos e linhas inválidas
                    if not linha[0] or 'UF' in linha[0] or 'Nome Município' in linha[0] or "VALORES DE TERRA" in linha[0]:
                        continue

                    # Extrair UF e município
                    uf = linha[0].strip().upper() if linha[0] else None
                    municipio = normalizar_texto(linha[1]) if linha[1] else None

                    # Criar chave de busca para o mapeamento
                    chave_busca = f"{municipio} - {uf}" if municipio and uf else municipio

                    # Corrigir nome do município usando o mapeamento
                    municipio_corrigido = mapeamento_municipios.get(chave_busca, municipio)

                    # Extrair valores das colunas
                    lavoura_boa = linha[2] if linha[2] else None
                    lavoura_regular = linha[3] if linha[3] else None
                    lavoura_restrita = linha[4] if linha[4] else None
                    pastagem_plantada = linha[5] if linha[5] else None
                    silvicultura = linha[6] if linha[6] else None
                    fauna_flora = linha[7] if linha[7] else None

                    # Adicionar linha formatada à lista de dados
                    dados.append([
                        uf, municipio_corrigido, lavoura_boa, lavoura_regular, lavoura_restrita,
                        pastagem_plantada, silvicultura, fauna_flora
                    ])

    # Criar DataFrame com os dados extraídos
    colunas = [
        'UF', 'Nome Município', 'Lavoura Aptidão Boa', 'Lavoura Aptidão Regular',
        'Lavoura Aptidão Restrita', 'Pastagem Plantada',
        'Silvicultura ou Pastagem Natural', 'Preservação da Fauna e da Flora'
    ]
    df = pd.DataFrame(dados, columns=colunas)

    # Limpeza dos dados
    df = df.dropna(how='all')                                     # remover linhas totalmente vazias
    df = df.dropna(subset=['Nome Município'])                     # remover linhas sem município
    df = df.drop_duplicates(subset=['UF', 'Nome Município'])     # remover duplicatas

    # Aplica conversão para float nas colunas numéricas
    colunas_numericas = [
        'Lavoura Aptidão Boa', 'Lavoura Aptidão Regular', 'Lavoura Aptidão Restrita',
        'Pastagem Plantada', 'Silvicultura ou Pastagem Natural', 'Preservação da Fauna e da Flora'
    ]
    for col in colunas_numericas:
        if col in df.columns:
            df[col] = df[col].apply(converter_para_float)

    return df

# ==========================================
# ETAPA 1: DEFINIÇÃO DA FUNÇÃO (Tudo com recuo/indentação)
# ==========================================

def extrair_dados_pdf_formatado(caminho_pdf):
    # 1. Mapeamento e extração do PDF
    df_xlsx = df_codes.copy()
    df_xlsx["Nome_Normalizado"] = (
        df_xlsx["Município"].apply(normalizar_texto) + " - " + df_xlsx["UF"].str.upper()
    )
    mapeamento_municipios = dict(zip(df_xlsx["Nome_Normalizado"], df_xlsx["MunicípioUF"]))

    dados = []
    with pdfplumber.open(caminho_pdf) as pdf:
        for pagina in pdf.pages:
            tabelas = pagina.extract_tables()
            for tabela in tabelas:
                for linha in tabela:
                    if not linha[0] or 'UF' in linha[0] or 'Nome Município' in linha[0] or "VALORES DE TERRA" in linha[0]:
                        continue

                    uf = linha[0].strip().upper() if linha[0] else None
                    municipio = normalizar_texto(linha[1]) if linha[1] else None
                    chave_busca = f"{municipio} - {uf}" if municipio and uf else municipio
                    municipio_corrigido = mapeamento_municipios.get(chave_busca, municipio)

                    dados.append([
                        uf, municipio_corrigido, linha[2], linha[3], linha[4],
                        linha[5], linha[6], linha[7]
                    ])

    colunas = [
        'UF', 'Nome Município', 'Lavoura Aptidão Boa', 'Lavoura Aptidão Regular',
        'Lavoura Aptidão Restrita', 'Pastagem Plantada',
        'Silvicultura ou Pastagem Natural', 'Preservação da Fauna e da Flora'
    ]
    df = pd.DataFrame(dados, columns=colunas)
    df = df.dropna(how='all')
    df = df.dropna(subset=['Nome Município'])
    df = df.drop_duplicates(subset=['UF', 'Nome Município'])

    # 2. Loop de conversão dos valores monetários (Ainda DENTRO da função - 4 espaços)
    colunas_valores = [
        'Lavoura Aptidão Boa', 'Lavoura Aptidão Regular', 'Lavoura Aptidão Restrita',
        'Pastagem Plantada', 'Silvicultura ou Pastagem Natural', 'Preservação da Fauna e da Flora'
    ]
    for coluna in colunas_valores:
        if coluna in df.columns:
            df[coluna] = df[coluna].apply(converter_para_float)

    # 3. Retorno do DataFrame pronto 
    return df
# ==========================================
# ETAPA 2: DOWNLOAD E EXECUÇÃO 
# ==========================================

url_pdf = 'https://drive.google.com/uc?id=1K253ieRmGqwdtpa0tiLl7YE5NUU6UmFO'
pdf_path = 'Planilha VTN 2025 para publicação 5.pdf'

# Download do arquivo
gdown.download(url_pdf, pdf_path, quiet=False)

# Chamada da função (AGORA SIM, após ela estar 100% construída acima)
df_dados = extrair_dados_pdf_formatado(pdf_path)
# ==========================================
# EXECUÇÃO (Fora da função - encostado na esquerda)
# ==========================================

# Executar extração e conversão
df_dados = extrair_dados_pdf_formatado(pdf_path)  #### 2.766 Municípios usados para calcular as médias por UF

# Corrigir nome de município com erro de OCR
df_dados['Nome Município'] = df_dados['Nome Município'].replace("C+A2:I2722ORURIPE", "Coruripe - AL")

# Definir colunas para cálculo da média
colunas_para_media = [
    'Lavoura Aptidão Boa', 'Lavoura Aptidão Regular', 'Lavoura Aptidão Restrita',
    'Pastagem Plantada', 'Silvicultura ou Pastagem Natural', 'Preservação da Fauna e da Flora'
]
# Calcular média por estado (UF)
media_VTN_estados = df_dados.groupby('UF')[colunas_para_media].mean().reset_index()

# Mesclar dados do MAPBIOMAS com dados VTN por município (temos 2.776 municípios com informação)
MAPBIOMAS_VTN_Municípios = pd.merge(
    Mapbiomas_municípios,       # DataFrame com municípios e dados MAPBIOMAS
    df_dados,                   # DataFrame com dados de VTN por município
    left_on='MunicípioUF',      # chave de junção no primeiro DataFrame
    right_on='Nome Município',  # chave de junção no segundo DataFrame
    how='left'                  # tipo de junção: todos os registros do datafram à esquerda
)

# Eliminando colunas duplicadas
MAPBIOMAS_VTN_Municípios.rename(columns={'UF_x': 'UF'}, inplace=True)
MAPBIOMAS_VTN_Municípios.drop(columns=['UF_y'], inplace=True)
MAPBIOMAS_VTN_Municípios.drop(columns=['Nome Município'], inplace=True)

# Alguns estados não têm informação - vamos preencher com médias de estados que os representam
# São acrescentados 6 estados e o DF

# Para AM: calcular a média dos estados RO, MT e PA
am_values = media_VTN_estados.loc[
    media_VTN_estados['UF'].isin(['RO', 'MT', 'PA'])
].mean(numeric_only=True)

# Para RR: calcular a média entre AM e PA
rr_values = (
    am_values + media_VTN_estados.loc[media_VTN_estados['UF'] == 'PA'].mean(numeric_only=True)
) / 2

# Para AC: usar o mesmo valor de AM
ac_values = am_values

# Para AP: usar o mesmo valor de PA
ap_values = media_VTN_estados.loc[media_VTN_estados['UF'] == 'PA'].mean(numeric_only=True)

# Para PB: usar o mesmo valor de PE
pb_values = media_VTN_estados.loc[media_VTN_estados['UF'] == 'PE'].mean(numeric_only=True)

# Para RN: usar o mesmo valor de CE
rn_values = media_VTN_estados.loc[media_VTN_estados['UF'] == 'CE'].mean(numeric_only=True)

# Para DF: usar o mesmo valor de GO
df_values = media_VTN_estados.loc[media_VTN_estados['UF'] == 'GO'].mean(numeric_only=True)

# Criar DataFrame com os novos estados e seus valores calculados
new_states = pd.DataFrame({
    'UF': ['AM', 'RR', 'AC', 'AP', 'PB', 'RN', 'DF'],
    'Lavoura Aptidão Boa': [
am_values['Lavoura Aptidão Boa'], rr_values['Lavoura Aptidão Boa'], ac_values['Lavoura Aptidão Boa'],
ap_values['Lavoura Aptidão Boa'], pb_values['Lavoura Aptidão Boa'], rn_values['Lavoura Aptidão Boa'],
df_values['Lavoura Aptidão Boa']
    ],
    'Lavoura Aptidão Regular': [
am_values['Lavoura Aptidão Regular'], rr_values['Lavoura Aptidão Regular'], ac_values['Lavoura Aptidão Regular'],
ap_values['Lavoura Aptidão Regular'], pb_values['Lavoura Aptidão Regular'], rn_values['Lavoura Aptidão Regular'],
df_values['Lavoura Aptidão Regular']
    ],
    'Lavoura Aptidão Restrita': [
am_values['Lavoura Aptidão Restrita'], rr_values['Lavoura Aptidão Restrita'], ac_values['Lavoura Aptidão Restrita'],
ap_values['Lavoura Aptidão Restrita'], pb_values['Lavoura Aptidão Restrita'], rn_values['Lavoura Aptidão Restrita'],
df_values['Lavoura Aptidão Restrita']
    ],
    'Pastagem Plantada': [
am_values['Pastagem Plantada'], rr_values['Pastagem Plantada'], ac_values['Pastagem Plantada'],
ap_values['Pastagem Plantada'], pb_values['Pastagem Plantada'], rn_values['Pastagem Plantada'],
df_values['Pastagem Plantada']
    ],
    'Silvicultura ou Pastagem Natural': [
am_values['Silvicultura ou Pastagem Natural'], rr_values['Silvicultura ou Pastagem Natural'],
ac_values['Silvicultura ou Pastagem Natural'], ap_values['Silvicultura ou Pastagem Natural'],
pb_values['Silvicultura ou Pastagem Natural'], rn_values['Silvicultura ou Pastagem Natural'],
df_values['Silvicultura ou Pastagem Natural']
    ],
    'Preservação da Fauna e da Flora': [
am_values['Preservação da Fauna e da Flora'], rr_values['Preservação da Fauna e da Flora'],
ac_values['Preservação da Fauna e da Flora'], ap_values['Preservação da Fauna e da Flora'],
pb_values['Preservação da Fauna e da Flora'], rn_values['Preservação da Fauna e da Flora'],
df_values['Preservação da Fauna e da Flora']
    ]
})

# Concatenar os novos estados ao DataFrame original
media_VTN_estados = pd.concat([media_VTN_estados, new_states], ignore_index=True)

"""# Completar VTN por município - Municípios sem VTN recebem VTN médio do estado."""

# Merge temporário
df_temp = MAPBIOMAS_VTN_Municípios.merge(
    media_VTN_estados,
    on='UF',
    suffixes=('', '_media')
)

# Para cada IMÓVEL, preenche os FALTANTES com a média do estado
for col in ['Lavoura Aptidão Boa','Lavoura Aptidão Regular','Lavoura Aptidão Restrita',
            'Pastagem Plantada','Silvicultura ou Pastagem Natural',
            'Preservação da Fauna e da Flora']:
    df_temp[col] = df_temp[col].fillna(df_temp[f'{col}_media'])

# Remove as colunas auxiliares
df_temp = df_temp.drop(columns=[f'{col}_media' for col in
            ['Lavoura Aptidão Boa','Lavoura Aptidão Regular','Lavoura Aptidão Restrita',
             'Pastagem Plantada','Silvicultura ou Pastagem Natural',
             'Preservação da Fauna e da Flora']])

MAPBIOMAS_VTN_FULL = df_temp.copy()

"""# Dataframe PROPRIEDADES"""
def ajustar_formato_numerico_area_total(valor):
    if pd.isnull(valor):
        return valor
    try:
        return float(valor.replace('.', '').replace(',', '.'))
    except ValueError:
        return None

def ajustar_percentual_detencao(valor):
    try:
        return float(valor) / 100
    except ValueError:
        return None

@st.cache_data
def carregar_dados(uf_selecionado):
    # Dicionário que mapeia cada UF para o ID do arquivo no Google Drive
    file_ids = {
        'AC': '10BbOX0KzIO69uZ4zA342I1quNfhtbt6-',
        'AL': '1_XNW2R6YAefjAZhtKCA3zvNfhvxcBGPB',
        'AM': '1O_ZD-2tqiBxalNtS6eLIn7ZazGbgS0nL',
        'AP': '1q3GXM1iKkel93ENoYsgbuRO8YSBv023K',
        'BA': '1pPIpQ4k-CBeJxWI_GNBj4_NA6UqFqdR7',
        'CE': '1v-ToNAgvTzECBgERz2jWvUVngs4xImeW',
        'DF': '1H4AXsI0J0hN7zBS_FTuOdnNiTpFeB7cS',
        'ES': '13n-ppcfdMgUI55OwtRLPCWa3JVdArhy-',
        'GO': '1PpPgHXC4byasmZ6w996_8defI-Jm27Ez',
        'MA': '1IjWENaIgxtOCLjOv7241ZN6h5Ogg2H-j',
        'MG': '1ZXtNI8MihMoDo3i87C5Nutb7qzVzb4zI',
        'MS': '1Wpiye7atJwV8G6I2SNGe5_CJJ2-aDzHV',
        'MT': '12hsLbs_r5UnyBjDN-hE_TusNaxCSVicx',
        'PA': '1PpzUpHoHhGAUW21rqYon1NhBFcDO9K2E',
        'PB': '1VMmExlxsopXQCSc_YVOv8wI858rz1qII',
        'PE': '1HOrUl9847ogubFnVWADoFkZshCrXXkCi',
        'PI': '1QH0KN2P9DoqvsuVwu54KqmA4BGoz8qm3',
        'PR': '18WH_NrscfCo_ZDYc3WTUfa4rCpM7InyQ',
        'RJ': '1XYI_ZgdXrFVmMlfdlEAYMWnX55nN_7C2',
        'RN': '1sgcS7CNkOGyjGHm7da9VVurP37aFf9eq',
        'RO': '1zHDkAKdUlygAd4Y4YTUg7WXFHsDxlUMq',
        'RR': '1wpopqOOOZURSb5j2o10DziTzUXwtu0QZ',
        'RS': '1V_MFD6LhgMFaicOti5rYBBw9n5Uni3E9',
        'SC': '1dOtvZaPbDduhGHhe9nv9F-Qs-wEcicuD',
        'SE': '1ymcIAgEfB1d43518gVgEc457IwPWfrXb',
        'SP': '17JnfFF0bdnr35jv_Cgk6o_hTpyeCKz2P',
        'TO': '1ZqCdOgxftE0PjuyOcdt87cX56-OQ9MBc'
    }

    column_names = [
        "CÓDIGO DO IMOVEL", "DENOMINAÇÃO DO IMÓVEL", "CÓDIGO DO MUNICÍPIO (IBGE)", "MUNICÍPIO",
        "UF", "AT IMÓVEL", "TITULAR", "NATUREZA JURÍDICA", "CONDIÇÃO DA PESSOA",
        "PERCENTUAL DE DETENÇÃO", "PAÍS"
    ]
    dtype_dict = {
        "CÓDIGO DO IMOVEL": str,
        "CÓDIGO DO MUNICÍPIO (IBGE)": str,
        "PERCENTUAL DE DETENÇÃO": str
    }
    
    df_list = []

    # Se selecionar 'BR', carregar todos os estados, senão carregar apenas o estado desejado
    estados_para_carregar = file_ids.keys() if uf_selecionado == 'BR' else [uf_selecionado]

    for uf in estados_para_carregar:
        file_id = file_ids[uf]
        url = f"https://drive.google.com/uc?id={file_id}"
        output = f"{uf}.csv"
        # Só faz o download se o arquivo local ainda não existir
        if not os.path.exists(output):
            gdown.download(url, output, quiet=False, fuzzy=True)
            
        # Ler o CSV
        df = pd.read_csv(output, sep=";", header=None, names=column_names,
                 dtype=dtype_dict, low_memory=False, encoding="latin-1")

        df = df.iloc[1:]  #Descarta a primeira linha 

        # Ajustes de formato
        df["AT IMÓVEL"] = df["AT IMÓVEL"].apply(ajustar_formato_numerico_area_total)
        df["PERCENTUAL DE DETENÇÃO"] = df["PERCENTUAL DE DETENÇÃO"].apply(ajustar_percentual_detencao)
        df["ÁREA DE DETENÇÃO"] = df["AT IMÓVEL"] * df["PERCENTUAL DE DETENÇÃO"]
        df['VERIFICAÇÃO'] = (df["ÁREA DE DETENÇÃO"] <= 2).astype(int)

        df_list.append(df)

    df_concatenado = pd.concat(df_list, ignore_index=True)
    return df_concatenado
    
# Escolha o estado desejado (exemplo: 'SP' para São Paulo ou 'BR' para todos)
uf_selecionado = 'BR'  # Altere para o estado desejado ou 'BR' para todos os estados

# Carregar os dados do estado selecionado
df_brasil = carregar_dados(uf_selecionado)

# Consolidar os dados por CÓDIGO DO IMOVEL
df_final = df_brasil.groupby(
    ["CÓDIGO DO IMOVEL", "DENOMINAÇÃO DO IMÓVEL", "CÓDIGO DO MUNICÍPIO (IBGE)", "MUNICÍPIO", "UF"],
    as_index=False
).agg({"AT IMÓVEL": "first"})  # Pega o primeiro valor válido de ÁREA TOTAL para cada imóvel

PROPRIEDADES = df_final

"""# Dataframe Final - Cada PROPRIEDADE recebe dados do MAPBIOMAS e VTN de seu MUNICÍPIO"""

# Converter a coluna 'CÓDIGO DO MUNICÍPIO (IBGE)' para int64 no segundo dataframe, usando .loc
PROPRIEDADES.loc[:, 'CÓDIGO DO MUNICÍPIO (IBGE)'] = PROPRIEDADES['CÓDIGO DO MUNICÍPIO (IBGE)'].astype(int)

# Agora realizar o merge
PROPRIEDADES_BIO_VTN = pd.merge(PROPRIEDADES, MAPBIOMAS_VTN_FULL,
                    left_on='CÓDIGO DO MUNICÍPIO (IBGE)',
                    right_on='Código IBGE',
                    how='inner')

# Eliminando colunas duplicadas
PROPRIEDADES_BIO_VTN.rename(columns={'UF_x': 'UF'}, inplace=True)
PROPRIEDADES_BIO_VTN.drop(columns=['UF_y'], inplace=True)
PROPRIEDADES_BIO_VTN.drop(columns=['MUNICÍPIO'], inplace=True)

PROPRIEDADES_FINAL=PROPRIEDADES_BIO_VTN.copy()

"""## EXCLUSÃO DE MUNICÍCIPIOS COM ISENÇÃO

# Municípios SEMIÁRIDO
"""
def baixar_e_ler_semiarido():
    url = "https://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/semiarido_brasileiro/Situacao_2022/lista_municipios_Semiarido_2022.xlsx"
    filename = "Semiarido_2022.xlsx"

    try:
        # Baixando o arquivo
        response = requests.get(url)

        with open(filename, 'wb') as f:
            f.write(response.content)
   
        # Lendo o arquivo com pandas
        df = pd.read_excel(filename)
        return df

    except Exception as e:
        print(f"Ocorreu um erro: {e}")
        return None

if __name__ == "__main__":
    df_municipios = baixar_e_ler_semiarido()

# Garantir que os códigos IBGE estejam no formato string em ambos os DataFrames
df_municipios["CD_MUN"] = df_municipios["CD_MUN"].astype(str)
PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"] = PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"].astype(str)

# Seleciona os municípios do Semiárido
mask_municipios = PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"].isin(df_municipios["CD_MUN"])

# Remove os que estão em df_municipios E têm AreaTotal <= 50
PROPRIEDADES_FINAL = PROPRIEDADES_FINAL[~(mask_municipios & (PROPRIEDADES_FINAL["AT IMÓVEL"] <= 50))]

"""Listando Propriedades ISENTAS E TRUBUTÁVEIS da Amazônia: Ocidental <= 100 e Oriental <=50"""

# Listas de UFs
ufs_amaz_ocidental = ["AC", "AM", "RO", "RR"]
ufs_amaz_oriental  = ["AP", "MA", "PA", "TO"]

# Regra para identificar propriedades isentas de ITR na Amazônia
PROPRIEDADES_FINAL["isenta"] = (
((PROPRIEDADES_FINAL["UF"].isin(ufs_amaz_ocidental)) & (PROPRIEDADES_FINAL["AT IMÓVEL"] <= 100)) |
((PROPRIEDADES_FINAL["UF"].isin(ufs_amaz_oriental))  & (PROPRIEDADES_FINAL["AT IMÓVEL"] <= 50))
)

# Mantém apenas registros não isentos
PROPRIEDADES_FINAL = PROPRIEDADES_FINAL[~PROPRIEDADES_FINAL["isenta"]]
PROPRIEDADES_FINAL.info()

"""Listando Propriedades ISENTAS E TRUBUTÁVEIS do PANTANAL: <= 100 e >100"""

# LEITURA PANTANAL
file_path_pantanal = "https://drive.google.com/uc?id=1N2PnMtUBwHV5hXXyFMTRs8jrxzaftcsG"
gdown.download(file_path_pantanal, "Pantanal.xlsx", quiet=False)

# file_path_pantanal = '/content/drive/MyDrive/ENTRADAS ITR/Pantanal.xlsx'
# Carregar a planilha

df_pantanal = pd.read_excel(file_path_pantanal, engine="openpyxl")

# Garantir que os códigos IBGE estejam no formato string em ambos os DataFrames
df_pantanal["COD_IBGE"] = df_pantanal["COD_IBGE"].astype(str)
PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"] = PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"].astype(str)

# Retirar municipios do SEMIARIDO com AT de até 50 Hectares

# Seleciona os municípios do Semiárido
mask_pantanal = PROPRIEDADES_FINAL["CÓDIGO DO MUNICÍPIO (IBGE)"].isin(df_pantanal["COD_IBGE"])

# Remove os que estão em df_municipios E têm AreaTotal <= 50
PROPRIEDADES_FINAL = PROPRIEDADES_FINAL[~(mask_pantanal & (PROPRIEDADES_FINAL["AT IMÓVEL"] <= 100))]

# Eliminando colunas duplicadas
PROPRIEDADES_FINAL.drop(columns=['Código IBGE'], inplace=True)
PROPRIEDADES_FINAL.drop(columns=['CD_MUN'], inplace=True)
PROPRIEDADES_FINAL.drop(columns=['COD_IBGE'], inplace=True)

ITR_PROPRIEDADE = PROPRIEDADES_FINAL.copy()

"""# Proporção do tipo de composição do Município - será usado para TODAS as propriedade do minicípio."""

# Calculando as relativas porcentagens Floresta, Pastagem, Silvicultura e Lavouras para cada PROPRIEDADE

ITR_PROPRIEDADE.loc[:, '% Floresta Município'] = (ITR_PROPRIEDADE['Floresta'] / ITR_PROPRIEDADE['Área Total'])
ITR_PROPRIEDADE.loc[:, '% Pastagem Município'] = (ITR_PROPRIEDADE['Pastagem'] / ITR_PROPRIEDADE['Área Total'])
ITR_PROPRIEDADE.loc[:, '% Silvicultura Município'] = (ITR_PROPRIEDADE['Silvicultura'] / ITR_PROPRIEDADE['Área Total'])
ITR_PROPRIEDADE.loc[:, '% Lavouras Município'] = (ITR_PROPRIEDADE['Lavouras'] / ITR_PROPRIEDADE['Área Total'])

# Exibindo as primeiras linhas para verificar o resultado

ITR_PROPRIEDADE[['Floresta', 'Pastagem', 'Silvicultura', 'Lavouras', 'Área Total', '% Floresta Município', '% Pastagem Município', '% Silvicultura Município', '% Lavouras Município']].head()

# Multiplicando as porcentagens pela ÁREA TOTAL da Propriedade'

ITR_PROPRIEDADE.loc[:, 'Floresta Propriedade'] = ITR_PROPRIEDADE['% Floresta Município'] * ITR_PROPRIEDADE['AT IMÓVEL']
ITR_PROPRIEDADE.loc[:, 'Pastagem Propriedade'] = ITR_PROPRIEDADE['% Pastagem Município'] * ITR_PROPRIEDADE['AT IMÓVEL']
ITR_PROPRIEDADE.loc[:, 'Silvicultura Propriedade'] = ITR_PROPRIEDADE['% Silvicultura Município'] * ITR_PROPRIEDADE['AT IMÓVEL']
ITR_PROPRIEDADE.loc[:, 'Lavouras Propriedade'] = ITR_PROPRIEDADE['% Lavouras Município'] * ITR_PROPRIEDADE['AT IMÓVEL']

# Calculando a média das 3 colunas de lavouras e criando a nova coluna 'Lavoura Média'

ITR_PROPRIEDADE['Lavoura Média'] = ITR_PROPRIEDADE[['Lavoura Aptidão Boa', 'Lavoura Aptidão Regular', 'Lavoura Aptidão Restrita']].mean(axis=1)

# 1° Passo:
ITR_PROPRIEDADE['VTN Floresta'] = ITR_PROPRIEDADE['Floresta Propriedade'] * ITR_PROPRIEDADE['Preservação da Fauna e da Flora']
ITR_PROPRIEDADE['VTN Pastagem'] = ITR_PROPRIEDADE['Pastagem Propriedade'] * ITR_PROPRIEDADE['Pastagem Plantada']
ITR_PROPRIEDADE['VTN Silvicultura'] = ITR_PROPRIEDADE['Silvicultura Propriedade'] * ITR_PROPRIEDADE['Silvicultura ou Pastagem Natural']
ITR_PROPRIEDADE['VTN Lavouras'] = ITR_PROPRIEDADE['Lavouras Propriedade'] * ITR_PROPRIEDADE['Lavoura Média']
ITR_PROPRIEDADE['VTN Total'] = ITR_PROPRIEDADE[['Lavoura Média', 'VTN Floresta', 'VTN Pastagem', 'VTN Silvicultura', 'VTN Lavouras']].sum(axis=1)

# 2° Passo
ITR_PROPRIEDADE['Quociente'] =((ITR_PROPRIEDADE['Pastagem Propriedade'] +
                                ITR_PROPRIEDADE['Lavouras Propriedade'] +
                                ITR_PROPRIEDADE['Silvicultura Propriedade']) /
                                ITR_PROPRIEDADE['AT IMÓVEL'])
ITR_PROPRIEDADE['VTN tributável'] = ITR_PROPRIEDADE['VTN Total'] * ITR_PROPRIEDADE['Quociente']
ITR_PROPRIEDADE['GU_CALC'] =((ITR_PROPRIEDADE['Pastagem Propriedade'] +
                              ITR_PROPRIEDADE['Lavouras Propriedade'] +
                              ITR_PROPRIEDADE['Silvicultura Propriedade']) /
                              ITR_PROPRIEDADE[ 'AT IMÓVEL'])

ITR_PROPRIEDADE['GU_FIXO'] = 1

# Filtrar registros com GU_FIXO > 0 e GU_CALC = NaN
filtro = (ITR_PROPRIEDADE['GU_CALC'] ==0) & (ITR_PROPRIEDADE['GU_FIXO']>0)

# CONTAGEM ALOCANDO NÚMERO DE PROPRIEDADES POR ÁRA DO IMÓVEL/GRAU DE UTLIZAÇÃO - GU_CALCULADO
# com colunas: 'AT_IMOVEL' e 'GU'

# Definir faixas de área total
bins_area = [0, 50, 200, 500, 1000, 5000, float('inf')]
labels_area = ['Até 50', '50+ até 200', '200+ até 500', '500+ até 1.000', '1.000+ até 5.000', 'Acima de 5.000']
ITR_PROPRIEDADE['Faixa_AT'] = pd.cut(ITR_PROPRIEDADE['AT IMÓVEL'], bins=bins_area, labels=labels_area, right=True)

# Definir faixas de grau de utilização GU CALCULADO
bins_gu = [0, 0.30, 0.50, 0.65, 0.80, float('inf')]
labels_gu = ['Até 30', '30+ até 50', '50+ até 65', '65+ até 80', '80+']
ITR_PROPRIEDADE['Faixa_GU'] = pd.cut(ITR_PROPRIEDADE['GU_CALC'], bins=bins_gu, labels=labels_gu, right=True)

# Definir faixas de grau de utilização GU FIXO
bins_gu = [0, 0.30, 0.50, 0.65, 0.80, float('inf')]
labels_gu = ['Até 30', '30+ até 50', '50+ até 65', '65+ até 80', '80+']
ITR_PROPRIEDADE['Faixa_GU'] = pd.cut(ITR_PROPRIEDADE['GU_FIXO'], bins=bins_gu, labels=labels_gu, right=True)

# CAULCULO DAS ALIQUOTAS - USANDO GU FIXO e GU CALCULADO

faixas = [
    (50, [(0.3, 0.01), (0.5, 0.007), (0.65, 0.004), (0.8, 0.002), (float("inf"), 0.0003)]),
    (200, [(0.3, 0.02), (0.5, 0.014), (0.65, 0.008), (0.8, 0.004), (float("inf"), 0.0007)]),
    (500, [(0.3, 0.033), (0.5, 0.023), (0.65, 0.013), (0.8, 0.006), (float("inf"), 0.0010)]),
    (1000, [(0.3, 0.047), (0.5, 0.033), (0.65, 0.019), (0.8, 0.0085), (float("inf"), 0.0015)]),
    (5000, [(0.3, 0.086), (0.5, 0.06), (0.65, 0.034), (0.8, 0.016), (float("inf"), 0.0030)]),
    (float("inf"), [(0.3, 0.20), (0.5, 0.12), (0.65, 0.064), (0.8, 0.03), (float("inf"), 0.0045)])
]

# Função para calcular aliquota usando GU_FIXO
def calcular_aliquota_fixa(row):
    AT = row["AT IMÓVEL"]
    GU_FIXO = row["GU_FIXO"]

    for limite_area, gu_faixas in faixas:
        if AT <= limite_area:
            for limite_gu, aliquota1 in gu_faixas:
                if GU_FIXO <= limite_gu:
                    return aliquota1
    return None  # caso não encontre nenhuma faixa

# Aplicando para GU_FIXO
ITR_PROPRIEDADE["Alíquota_fixa"] = ITR_PROPRIEDADE.apply(calcular_aliquota_fixa, axis=1)

# Função para calcular aliquota usando GU_CALC
def calcular_aliquota_calc(row):
    AT = row["AT IMÓVEL"]
    GU_CALC = row["GU_CALC"]

    for limite_area, gu_faixas in faixas:
        if AT <= limite_area:
            for limite_gu, aliquota2 in gu_faixas:
                if GU_CALC <= limite_gu:
                    return aliquota2
    return None

# Aplicando para GU_CALC
ITR_PROPRIEDADE["Alíquota_calc"] = ITR_PROPRIEDADE.apply(calcular_aliquota_calc, axis=1)

# 5° Passo:
ITR_PROPRIEDADE['ITR_GU_FIXO'] = ITR_PROPRIEDADE['VTN tributável'] * ITR_PROPRIEDADE['Alíquota_fixa']
ITR_PROPRIEDADE['ITR_GU_CALC'] = ITR_PROPRIEDADE['VTN tributável'] * ITR_PROPRIEDADE['Alíquota_calc']
